# typed: false
# frozen_string_literal: true

# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class TokenCount < Formula
  desc "Count tokens for LLM models using exact tokenization"
  homepage "https://github.com/shaunburdick/token-count"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.3.0/token-count-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "e26f65479d874b96d0274a94fd1075216bead1aa4934a8cab715bc591417e9c6"
    end
    on_arm do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.3.0/token-count-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "e0d33a33742122bfa127117db6cfd49381931265494d73f80279f15805fc056f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.3.0/token-count-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c022b25da41352681c8ce4634163d500279f6b3fca169cb3f88421fae234d5d6"
    end
  end

  def install
    bin.install "token-count"
  end

  test do
    assert_match "token-count #{version}", shell_output("#{bin}/token-count --version")
    
    # Test basic functionality
    output = pipe_output("#{bin}/token-count", "Hello, world!")
    assert output.to_i > 0, "Expected token count > 0"
  end
end
