# typed: false
# frozen_string_literal: true

# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class TokenCount < Formula
  desc "Count tokens for LLM models using exact tokenization"
  homepage "https://github.com/shaunburdick/token-count"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.2.2/token-count-0.2.2-x86_64-apple-darwin.tar.gz"
      sha256 ""
    end
    on_arm do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.2.2/token-count-0.2.2-aarch64-apple-darwin.tar.gz"
      sha256 ""
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shaunburdick/token-count/releases/download/v0.2.2/token-count-0.2.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "token-count"
  end

  test do
    assert_match "token-count #{version}", shell_output("#{bin}/token-count --version")
    
    # Test basic functionality
    output = pipe_output("#{bin}/token-count", "Hello, world!")
    assert output.to_i > 0, "Expected token count > 0"
  end
end
