# typed: false
# frozen_string_literal: true

# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class TokenCount < Formula
  desc "Count tokens for OpenAI API requests"
  homepage "https://github.com/shaunburdick/token-count"
  url "https://github.com/shaunburdick/token-count/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "50649f7c4c66a999577aaac2ff71fc1cb421d8c10d363e46025e0b3e10f69e8a"
  license "MIT"
  head "https://github.com/shaunburdick/token-count.git", branch: "main"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--root", prefix, "--path", "."
  end

  test do
    assert_match "token-count #{version}", shell_output("#{bin}/token-count --version")

    # Test basic functionality
    output = pipe_output("#{bin}/token-count", "Hello, world!")
    assert output.to_i > 0, "Expected token count > 0"
  end
end